### ISSUE TITLE
Specific pattern not solved

### ISSUE THREAD

**Issue by wolfgangw** [hkociemba/CubeExplorer#2]
[not_solved.txt](https://github.com/hkociemba/CubeExplorer/files/3312785/not_solved.txt)

Solve does not lead to a clean cube. What am I missing?

**Comment by wolfgangw** [comment]
![not_solved](https://user-images.githubusercontent.com/184025/59893634-d4dfc100-93dd-11e9-8d8a-2a9a3b650e79.JPG)

**Comment by hkociemba** [comment]
Sorry but I do not understand what's your problem. Please be more specific.
