### ISSUE TITLE
Implementing a Thistlethwaite solver?

### ISSUE THREAD

**Issue by TheIrishBub** [hkociemba/CubeExplorer#3]
I wonder if a Thistlethwaite solver is something that could be implemented into Cube Explorer? If not, that's fine, but I think this might be a cool feature.

**Comment by hkociemba** [comment]
I do not see why this is a cool feature. The two phase algorithm reduces the 4 steps of a Thistlethwaite solver to 2 steps and additionally finds suboptimal solution in step 1 to find better overall solutions.
